# Generated by Django 3.0.6 on 2020-05-27 11:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('phone', models.BigIntegerField()),
                ('address', models.CharField(max_length=100)),
                ('designation', models.CharField(max_length=20)),
                ('experience', models.CharField(max_length=20)),
                ('age', models.IntegerField()),
                ('currentsalary', models.CharField(max_length=20)),
                ('demandsalary', models.CharField(max_length=20)),
                ('educationlevel', models.CharField(max_length=20)),
                ('profilepic', models.ImageField(default='profile.jpg', upload_to='profile_pics')),
                ('aboutme', models.CharField(max_length=200)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AccountType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Company', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
