# Generated by Django 3.0.6 on 2020-06-05 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_portal', '0002_auto_20200531_1738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skills',
            name='skillname',
            field=models.CharField(max_length=10),
        ),
    ]
