# Generated by Django 3.0.6 on 2020-06-10 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_portal', '0003_auto_20200605_1045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skills',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_portal.Profile'),
        ),
    ]
