# Generated by Django 3.0.6 on 2020-06-17 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_portal', '0006_education'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='percentage',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='skills',
            name='skillLevel',
            field=models.SmallIntegerField(default=0),
        ),
    ]
