# Generated by Django 3.0.6 on 2020-06-23 13:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_portal', '0008_experience_projects'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CompanyName', models.CharField(max_length=50)),
                ('Email', models.EmailField(max_length=50)),
                ('Contact', models.BigIntegerField(null=True)),
                ('Address', models.CharField(max_length=100)),
                ('CompanyType', models.CharField(max_length=20)),
                ('Website', models.CharField(max_length=30)),
                ('TotalEmployees', models.IntegerField()),
                ('EstablishedIn', models.IntegerField()),
                ('CompanyLogo', models.ImageField(default='profile_pics\\Company img.jpg', upload_to='profile_pics')),
                ('AboutCompany', models.CharField(max_length=300)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
