# Generated by Django 3.0.6 on 2020-06-30 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_portal', '0009_comprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comprofile',
            name='EstablishedIn',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='comprofile',
            name='TotalEmployees',
            field=models.IntegerField(null=True),
        ),
    ]
