# Generated by Django 3.0.6 on 2020-07-13 14:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_portal', '0010_auto_20200630_1927'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostJob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('JobTitle', models.CharField(max_length=20)),
                ('IndustryArea', models.CharField(max_length=15)),
                ('MonthlySalary', models.CharField(max_length=50)),
                ('Location', models.CharField(max_length=30)),
                ('EmploymentType', models.CharField(max_length=15)),
                ('Designation', models.CharField(max_length=15)),
                ('Positions', models.CharField(max_length=5)),
                ('Experience', models.CharField(max_length=15)),
                ('Gender', models.CharField(max_length=10)),
                ('Nationality', models.CharField(max_length=15)),
                ('JobDetail', models.CharField(max_length=300)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
