# Generated by Django 3.0.6 on 2020-10-07 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_portal', '0013_auto_20200928_1749'),
    ]

    operations = [
        migrations.AddField(
            model_name='postjob',
            name='CompanyName',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
